language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"

env:
  - DEPS="Django>=1.11,<1.12"
  - DEPS="Django>=2.0,<2.1"
  - DEPS="Django>=2.1,<2.2"

install:
	- pip install --upgrade pip
  - pip install pipenv coveralls
  - pipenv install --dev
  - pipenv run pip install -e .
  - pipenv run pip install $DEPS

script: pipenv run py.test --cov

after_success:
  - coverage report
  - coveralls
