language: python

python:
  - "3.4"
  - "3.5"

env:
  - DJANGO_VERSION=1.8.x
  - DJANGO_VERSION=1.9.x

install:
  - pip install tox

script:
  - tox -e "$TRAVIS_PYTHON_VERSION-$DJANGO_VERSION"

after_success:
  - pip install coveralls
  - coverage report
  - coveralls
