[tool.black]
target-version = ['py35', 'py36', 'py37', 'py38']
exclude = '(/migrations/)|(/node_modules/)|(howl/settings.py)'
skip-numeric-underscore-normalization = true

[tool.isort]
known_first_party = ['howl']
sections = ['FUTURE', 'STDLIB', 'THIRDPARTY', 'FIRSTPARTY', 'LOCALFOLDER']
default_section = 'THIRDPARTY'
skip_glob = ['**/migrations/**', '**/node_modules/**']
line_length = 88
use_parantheses = 'True'
include_trailing_comma = 'True'
multi_line_output = 3
