# Generated by Django 2.1.7 on 2019-03-30 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('howl', '0009_auto_20181208_0351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchdog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('observer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='howl.Observer')),
            ],
        ),
    ]
